[package]
name = "bridge"
version = "0.7.1"
edition = "2021"
authors = ["Agustin Marcelo Marco Bacigalupo <01marcoagustin@gmail.com>"]
license = "MIT"

[dependencies]
iced = { workspace = true }
backend = { path = "../backend" }
tracing = { workspace = true }
